name = "soehne-investment"
compatibility_date = "2026-07-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "soehne-investment"
database_id = "924c6355-a172-4b75-a8d0-6358369d7bf8"
